### PR TITLE
Java 6 compatability fix.

### PR DESCRIPTION
**Pull request by djozis**
Commit to resolve Java 6 compatability issue: https://github.com/xtext/xtext-gradle-plugin/issues/44

### CODE REVIEW

**Comment by djozis** [comment]
Perhaps this should have checked against AutoCloseable now that I think about it. Perhaps it doesn't matter.

**Comment by oehme** [comment]
Thank you for looking into this! :)

There are other places in the intellij plugin where we use Java 7 API (`Files.copy`). Extra points if you could get rid of those.

Also to make sure we actually don't use any Java 7 APIs, it would make sense to adjust the travis configuration to build on Java 6.

**Comment by djozis** [comment]
Unfortunately I believe you are using other Gradle plugins which target Java 7 bytecode, so using Java 6 would fail.
I've never used IntelliJ, let alone the plugin, so that may be an issue for another time, or another contributor. I may still give it a go another day.
Is it ok to treat the IntelliJ Java 6 issue separately?

**Comment by Buggaboo** [comment]
tip: use [jenv](http://www.jenv.be/) to switch quickly between jdk versions.

Usage: `jenv shell 1.7` or 1.6 or 1.8...

**Comment by oehme** [comment]
Thank you for the fix, I will publish a patch release now.

**Pull request merged**
