### PR TITLE
[#108][#131] ship custom IWorkspaceConfig to be compatible with multiple Xtext versions

### PR DESCRIPTION
**Pull request by cdietrich**
[#108][#131] ship custom IWorkspaceConfig to be compatible with multiple Xtext versions

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@oehme where do i find the option. the problem is already there since 2.12.
so i wonder why we dont detect it. is it possible sometimes the bootstrap version wins. sometimes the runtime?

**Comment by cdietrich** [comment]
created https://github.com/xtext/xtext-gradle-plugin/pull/133
lets see if it fails

**Comment by oehme** [comment]
Nope, according to https://github.com/eclipse/xtext-core/commit/987146a77f45f7e157532473c3eef792035d1755 it was only removed in 2.15

**Comment by cdietrich** [comment]
correct. saw that wrong

**Pull request merged**
