### PR TITLE
#141 Replace Closure with Action<T>

### PR DESCRIPTION
**Pull request by sgarfinkel**
Task-Url: https://github.com/xtext/xtext-gradle-plugin/issues/141

### CODE REVIEW

**Comment by sgarfinkel** [comment]
It passed all tests, but I'm really not sure how to force the integration tests to use the Action overload over the Closure one. It's rather mysterious to me how Gradle's groovy build script selects which one to invoke.

**Comment by sgarfinkel** [comment]
@oehme @cdietrich Any action on this?

**Comment by cdietrich** [comment]
i wonder if there is a way to actually have kotlin dsl based tests. unfortunately i have zero experience with kotlin dsl

**Comment by sgarfinkel** [comment]
@cdietrich Agreed. I have no idea which implementation Gradle's groovy build scripts selects.

**Comment by cdietrich** [comment]
@oehme from groovy the old closures still be be called. is there an option in the buildscript to pick the new one?

**Comment by oehme** [comment]
Why would you?

**Comment by cdietrich** [comment]
So the assumption is that if we drop the closure it will be forward compatible

**Comment by oehme** [comment]
For build scripts yes. If someone statically compiled against us, no. But that's what major versions are for.

**Pull request merged**
