### PR TITLE
Upgrade the plugin to support modern Gradle versions

### PR DESCRIPTION
**Pull request by oehme**
- Use Property API instead of convention mapping
- Use JavaPluginExtension instead of JavaPluginConvention
- Insert XtendSourceDirectorySet as an extension instead of a convention
- Raise minimum Gradle version to 7.1
- Raise minimum Xtext version to 2.17 (first version to support Java 11)
- Raise minimum Java version to 11

### CODE REVIEW

**Comment by oehme** [comment]
I still plan to do some more changes, consistently using Gradle's `Property` API everywhere and maybe removing some of our other hacks. But the tests aganst Gradle 8 are already green, so if we merge this in its current state, I could make a 4.0 milestone release that you can test.

**Comment by cdietrich** [comment]
@oehme  is there an example how to use the new version of the plugin?

in the xtext codebase we do
> Cannot set the value of read-only property 'xtextClasspath' for task ':org.eclipse.xtend.core:generateXtext' of type org.xtext.gradle.tasks.XtextGenerate.

**Comment by oehme** [comment]
Since you want to overwrite the default classspath, use `setFrom` instead of `from`. `from` appends to the collection.

**Comment by cdietrich** [comment]
this still does not completely work in xtext-core
> Task :org.eclipse.xtext.testing:generateXtext
fails.

**Comment by cdietrich** [comment]
my wip of experiments is here:
github.com/eclipse/xtext-core/pull/new/cd_tryToFixForNewGradlePlugin

**Comment by cdietrich** [comment]
in yourkit i can see a lot of time spent here (as said am not sure if my changes to xtext-core are correct)



Bildschirmfoto vom 2023-02-20 19-57-08

**Comment by oehme** [comment]
I'll look into both these issues, thanks for the repro branch!

**Comment by cdietrich** [comment]
thx. will also create a call counting snapshot.

**Comment by cdietrich** [comment]
Bildschirmfoto vom 2023-02-20 21-02-36

**Comment by oehme** [comment]
Just FYI, you don't need to keep investigating this. I'm pretty sure I know what the problem is and will fix it this weekend. I don't have time to work on this project during weekdays.

**Comment by oehme** [comment]
@cdietrich I've pushed an update to your branch and fixed the issues you found. Please have another go :)

**Comment by cdietrich** [comment]
@oehme am getting now

```

FAILURE: Build failed with an exception.

* Where:
Script '/Users/cdietrich/tmp/xtext-core/gradle/eclipse-project-layout.gradle' line: 23

* What went wrong:
A problem occurred evaluating script.
> Could not set unknown property 'outputDir' for [[Ljava.lang.Object;@49e8ab4a, [Ljava.lang.Object;@5e2225bb] of type org.xtext.gradle.tasks.internal.DefaultXtextSourceDirectorySet.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

**Comment by cdietrich** [comment]
looks better now. will do some profiling though

**Comment by cdietrich** [comment]
yourkit no longer shows previous hotspots

**Review by cdietrich — APPROVED** [review]

**Comment by oehme** [comment]
I've released a milestone that you can try a bit more widely: https://github.com/xtext/xtext-gradle-plugin/releases/tag/4.0.0-m1

**Comment by cdietrich** [comment]
gonna adapt all xtext builds mid of next week

**Comment by cdietrich** [comment]
@oehme in xtext-extras branch  cd_testXtextGradlePlugin400M1

i still see 

```
> Task :org.eclipse.xtext.xbase:generateXtext FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':org.eclipse.xtext.xbase:generateXtext'.
> java.lang.NullPointerException (no error message)

Caused by: java.lang.NullPointerException
        at org.xtext.gradle.builder.XtextGradleBuilder.lambda$indexChangedClasspathEntries$5(XtextGradleBuilder.java:183)
        at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:42)

```

**Comment by cdietrich** [comment]
also

```
./gradlew -PuseJenkinsSnapshots=true generateXtend -PcompileXtend=true  --stacktrace
``` i the same branch in xtext-xtend fails (might also be a problem on master)
ususally we dont use generate mwe calls and compile xtend together

**Comment by cdietrich** [comment]
@oehme what is the replacement for
`fileExtension = 'hero'`
that was there before in Language?
`fileExtensions = ['hero']` ?

**Comment by oehme** [comment]
Yep, `fileExtension` was deprecated a while ago and replaced with the multi-valued `fileExtensions`

**Comment by oehme** [comment]
I'll look into the errors you mentioned.

**Comment by cdietrich** [comment]
one hint: junping between the builds of core, extras, xtend and web seems to cause the npe.
now i got it on xtext-xtend whilst was working on xtext-web before

**Comment by oehme** [comment]
Should be fixed with 4.0.0-m2 now.

**Comment by cdietrich** [comment]
can no longer see the npe problem.

**Comment by cdietrich** [comment]
also all builds in xtext-* seem to work fine

**Comment by oehme** [comment]
Any other checks you wanna run? Otherwise I'm going to push a release.

**Comment by cdietrich** [comment]
@szarnekow  do you still use gradle in any projects?

**Comment by szarnekow** [comment]
> @szarnekow do you still use gradle in any projects?

Nope, I don't.

**Comment by cdietrich** [comment]
i guess then we can go

**Comment by cdietrich** [comment]
many thanks @oehme

**Comment by kuniss** [comment]
Many thanks from a user, @oehme !

And a great thank you for all your persistent work on the Xtext stuff, @cdietrich !

**Pull request merged**
