### PR TITLE
Eliminate warnings and improve .gitignore

### PR DESCRIPTION
**Pull request by franzbecker**
When checking out the source code and importing it into Eclipse I get several warnings and artifacts that are not considered in the .gitignore.

The commits eliminate all warnings except for two (in DefaultXtextSourceDirectorySet which are caused by the Gradle API) and replaces the .gitignore by a generated one.

### CODE REVIEW

**Comment by oehme** [comment]
Thanks for getting rid of those warnings.

But what exactly was not considered in the .gitignore? That new one looks huge and I would rather stay with a simple one.

**Comment by franzbecker** [comment]
I put my workspace at the same path as the repository so it's basically only `.metadata`.
The one I committed here is generated using https://www.gitignore.io for Java, Gradle, Eclipse and IntelliJ which I prefer over hand-crafted ones.

Should I change it back and only add the `.metadata`?

**Comment by oehme** [comment]
Well many of the rules don't really make sense in this project (which is natural for a one-size-fits-all file). For instance, if I want to add some .jar file as test data, I would stumble over the *.jar exclude rule. I would never have added that rule myself, since I know all generated jars are in the /build folder.

So for Eclipse and Idea I guess only the following need to be added:

- .workspace
- .ipr/.iml/.idea

**Comment by franzbecker** [comment]
Agreed, I modified the .gitignore accordingly. Please check if this is ok for you.

**Comment by oehme** [comment]
Nice =) Thank you!

**Pull request merged**
